pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/man-surfing_lr3e-5_seed33"

train_data:
  data_dir: "/home/data/Kinetics/kinetics-400"
  mode: "train"
  labels:
    - "ice skating"
    - "ice climbing"
    - "jet skiing"
    - "kicking soccer ball"
    - "playing badminton"
    - "playing ice hockey"
    - "playing kickball"
    - "playing tennis"
    - "playing cricket"
    - "playing basketball"
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "a panda is playing basketball"
    - "a boy, wearing a birthday hat, is playing basketball"
    - "a raccoon is playing basketball, cartoon style"
    - "Iron Man is playing basketball in the desert"
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False
gradient_accumulation_steps: 4
